Update Project Structure Description & Fix Code Style
MarkBind/markbind pull request #1695
Opened 2021-12-18 15:49 UTC by kaixin-hc

**What is the purpose of this pull request?**

- [X] Documentation update
- [ ] Bug fix
- [ ] Feature addition or enhancement
- [ ] Code maintenance
- [ ] Others, please explain:

Fixes #1599 .

**Overview of changes:**
* Fix markdown to match code style ("Use generic numbering for ordered lists." + new line after header
* Update section under "The core library mainly houses:"
* Update the location of the CLI interface application.

**Anything you'd like to highlight / discuss:**
I'm new to the project, I hope I described the project structure accurately! I referred heavily to the architecture page in the developer guide and thought about what might have helped me when I started examining the project.

**Testing instructions:**

**Proposed commit message: (wrap lines at 72 characters)**
Update projectStructure.md

---

**Checklist:** :ballot_box_with_check:

- [X] Updated the documentation for feature additions and enhancements
- [ ] Added tests for bug fixes or features
- [ ] Linked all related issues
- [ ] No unrelated changes

2021-12-20 04:57 UTC, jonahtanjz requested changes
Thanks for updating the docs :) Looks quite detailed and accurate to me 👍

2021-12-20 04:57 UTC, jonahtanjz commented on docs/devGuide/design/projectStructure.md
> +1. Functions and libraries used to parse and process MarkBind into usable output are stored in `src` The architecture described in [Architecture](../design/architecture).html) is contained here. A br
```suggestion
1. Functions and libraries used to parse and process MarkBind into usable output are stored in `src` The architecture described in [Architecture](../design/architecture) is contained here. A brief rundown of what it includes:
```

2021-12-23 07:48 UTC, kaixin-hc commented
Thanks Jonah! I've made the change you suggested. The commit after that is to make sure the lists obey grammar conventions + rearranging the first list so that it has the same order as the section below for clarity.

2021-12-26 13:34 UTC, jonahtanjz approved these changes
Thanks for making the changes :) 

LGTM 👍

2021-12-27 08:30 UTC, merged