update workflow and project structure of devGuide
MarkBind/markbind pull request #1786
Opened 2022-02-21 14:42 UTC by tlylt

**What is the purpose of this pull request?**

- [x] Documentation update
- [ ] Bug fix
- [ ] Feature addition or enhancement
- [ ] Code maintenance
- [ ] Others, please explain:

**Overview of changes:**
Fixes #1707
- Add a tooltip that includes a link to Babel's readme on the pros and cons of a monorepo
- Update the project structure section to include some more details about the external packages, pointing out those that have been patched
- Update some points for consideration when adding dependencies, under workflow

Potentially fixes #1012
 - The issue asks for a list of markdown-it plugins & rules to be included in the DG. I have added some descriptions about existing markdown-it plugins and also refer to the `package.json` for a full list. I feel that this might just be enough without providing too many details as to which exact rules/plugins are used, which can be subjected to (somewhat frequent) changes across versions. However, if there is still merit, I shall remove this part.

**Anything you'd like to highlight / discuss:**
- The above point on whether this PR is sufficient to close the related issue.
- Any proofreading, thoughts on the added content is appreciated.

**Testing instructions:**
See the two pages in the dev guide that have been updated
- [workflow](https://deploy-preview-1786--markbind-master.netlify.app/devguide/workflow#points-for-consideration)
- [project structure](https://deploy-preview-1786--markbind-master.netlify.app/devguide/design/projectstructure)

**Proposed commit message: (wrap lines at 72 characters)**
Update workflow and project structure of devGuide

---

**Checklist:** :ballot_box_with_check:

- [ ] Updated the documentation for feature additions and enhancements
- [ ] Added tests for bug fixes or features
- [x] Linked all related issues
- [x] No unrelated changes

2022-02-22 07:16 UTC, ryoarmanda requested changes
Overall looks great! Some small things that we need to address first and we're all set :)

What you've done for the Points of Consideration part is good. About whether we include a list of our patches, I'm kind of on the fence about it and can be discussed with others (cc @jonahtanjz any thoughts?)

Most of the patches I think are quite documented in their respective files e.g. `live-server`, `nunjucks` (so devs can read the top-level comment for context), but having a list of it seems fine too to get an overall picture on what we have patched so far in the repo but therefore has to be continually updated whenever we add/remove something (though I don't think we have so many of it right now, save for the `markdown-it` stuff).

2022-02-22 07:19 UTC, ryoarmanda commented on docs/devGuide/workflow.md
> +Patching          | <ul><li>Quick - no need to maintain / publish more npm packages or setup release procedures etc</li><li>Ensure the changes propagate to other dependencies</li><li>Benefits of a mo
Maybe paraphrase the `Benefits of a monorepo` part to `Enjoy the benefits of monorepo`?

2022-02-22 07:25 UTC, tlylt commented on docs/devGuide/design/projectStructure.md
> -
Hi @ryoarmanda, I tried adding blank lines, but it seems to break the interpretation of a list and resulted in weird margins

2022-02-22 08:03 UTC, kaixin-hc commented
It looks good to me as well!

I think maintaining an active list isn't a good idea because of the maintaining will be difficult, and highlighting the relevant files as you have is a better choice.

I feel like [zeyu's extended explanation in the issue](https://github.com/MarkBind/markbind/issues/1707#issuecomment-1013679201) on why particular patches were patches instead of forks was really helpful though for giving context as to why these questions were questions that should be considered. Maybe some of that can be incorporated?

2022-02-22 08:16 UTC, ryoarmanda commented on docs/devGuide/design/projectStructure.md
> -
Hmm I see, this looks like a styling quirk, as you can do the same thing here in GitHub and get an evenly spaced list like below (see the raw if you would like).

> * First item
>   * First sub-item
>   * Second sub-item
>
> * Second item
>
> * Third item

The way to work around it right now is to add another blank line between the sub-items, which will give you the evenly spaced list as intended, but with a side effect of the sub-items being spaced out as well. You can try it out first, and see if it is still stylistically good. If not, then we can settle with no blank lines for now.

2022-02-22 11:28 UTC, tlylt commented on docs/devGuide/design/projectStructure.md
> -
Thanks for tip, fixed.

2022-02-23 08:35 UTC, jonahtanjz commented
> What you've done for the Points of Consideration part is good. About whether we include a list of our patches, I'm kind of on the fence about it and can be discussed with others (cc @jonahtanjz any thoughts?)

Agree with the rest, maintaining a full list of patches can be easy to miss out when they get updated, which can confuse some new devs when they are looking through. I think having a list of external libraries that we have patched/fork is sufficient in the workflow page. Perhaps can also include a link under "Points for consideration" to the list of external libraries in the workflow page?

2022-03-01 02:11 UTC, tlylt commented
Thanks for all the feedback given!
I have:
- fixed the list spacing issues in the project structure page
- put in a link from workflow to project structure
- edited some minor things based on the suggestions

> I feel like https://github.com/MarkBind/markbind/issues/1707#issuecomment-1013679201 on why particular patches were patches instead of forks was really helpful

I agree with this but am not too sure how to include it succinctly. Given that I have pointed out all the important external libraries used in the project structure, I am guessing this might be enough for readers to explore the relevant PRs/Issues. Also, I mentioned that
> Also, the rationales behind most existing patches are documented in their respective files, read them (and their respective PRs/issues) for more context!

I hope this is enough, but let me know if it isn't.

> maintaining a full list of patches can be easy to miss out when they get updated

I share the same feeling here, which is why I would like this PR to close #1012. I have mentioned the places to look for markdown-it related plugins and rules so readers can now locate them easily.

Please feel free to let me know if there are any further changes required.

2022-03-04 14:47 UTC, ryoarmanda approved these changes
Thanks for the further work! I think it looks good 👍

2022-03-06 04:50 UTC, merged