Set search bar width to placeholder text
MarkBind/markbind pull request #1959
Opened 2022-07-06 06:10 UTC by weiquu

**What is the purpose of this pull request?**

- [ ] Documentation update
- [x] Bug fix
- [ ] Feature addition or enhancement
- [ ] Code maintenance
- [ ] DevOps
- [ ] Improve developer experience
- [ ] Others, please explain:

Resolves #665 
Continuation of PR #1957 (was resetting the dist file changes)

**Overview of changes:**
Binds the width of the search bar to the length of the placeholder text so as to avoid clipping of the placeholder text.

Before:
![search bar before](https://user-images.githubusercontent.com/48304907/177129262-bd2b01c4-7604-4a46-88d5-57c778a89384.png)

After:
![search bar after](https://user-images.githubusercontent.com/48304907/177129303-efb6a89a-44fa-47b9-bfbe-3b5d88297cb1.png)

The minimum width of the search bar is set to its current width (i.e. the width in the "Before" screenshot above).

**Anything you'd like to highlight/discuss:**
The width is set using the `ch` unit, which is defined according to the width of the `o` character in a given typeface. Hence, it might run into issues with certain non-standard typefaces, should the MarkBind typeface be changed in the future.

**Testing instructions:**
Use a long placeholder text to check if the width of the search bar expands accordingly.

**Proposed commit message: (wrap lines at 72 characters)**
Set search bar width to placeholder text

---

**Checklist:** :ballot_box_with_check:

- [ ] Updated the documentation for feature additions and enhancements
- [ ] Added tests for bug fixes or features
- [ ] Linked all related issues
- [ ] No unrelated changes

2022-07-09 18:54 UTC, weiquu commented
Hello! I've switched to another method for setting the width which I think works better. It uses a temporary div and sets the text inside to the placeholder:
```
<div ref="placeholderDiv" class="form-control">
    {{ placeholder }}
</div>
```
After the page has loaded, it gets the width of the div and sets the search bar width to be the same as that. Then, the temporary div is removed:
```
mounted() {
    const { placeholderDiv } = this.$refs;
    this.placeholderDivWidth = placeholderDiv.offsetWidth;
    placeholderDiv.remove();
}
```
As suggested, I've also added in a minimum width of 12.7em and a maximum width of 25.4em.

This results in this behaviour for a short placeholder:
![very short placeholder](https://user-images.githubusercontent.com/48304907/178119167-192e2870-d8e7-48b6-8f8b-7d35d4b1f4f8.png)
This behaviour for a normal placeholder:
![normal placeholder](https://user-images.githubusercontent.com/48304907/178119175-b97422be-2969-4c18-8689-af97e3f4a1f8.png)
And this behaviour for a long placeholder:
![very long placeholder](https://user-images.githubusercontent.com/48304907/178119183-d911be13-bed0-41c4-b1a0-a164e0228f68.png)

Is this method fine, and should I commit the changes?

2022-07-10 08:39 UTC, tlylt commented
> Hello! I've switched to another method for setting the width which I think works better. It uses a temporary div and sets the text inside to the placeholder:
> 
> ```
> <div ref="placeholderDiv" class="form-control">
>     {{ placeholder }}
> </div>
> ```
> 
> After the page has loaded, it gets the width of the div and sets the search bar width to be the same as that. Then, the temporary div is removed:
> 
> ```
> mounted() {
>     const { placeholderDiv } = this.$refs;
>     this.placeholderDivWidth = placeholderDiv.offsetWidth;
>     placeholderDiv.remove();
> }
> ```
> 
> As suggested, I've also added in a minimum width of 12.7em and a maximum width of 25.4em.
> 
> This results in this behaviour for a short placeholder: ![very short placeholder](https://user-images.githubusercontent.com/48304907/178119167-192e2870-d8e7-48b6-8f8b-7d35d4b1f4f8.png) This behaviour for a normal placeholder: ![normal placeholder](https://user-images.githubusercontent.com/48304907/178119175-b97422be-2969-4c18-8689-af97e3f4a1f8.png) And this behaviour for a long placeholder: ![very long placeholder](https://user-images.githubusercontent.com/48304907/178119183-d911be13-bed0-41c4-b1a0-a164e0228f68.png)
> 
> Is this method fine, and should I commit the changes?

Hi, @weiquu sounds good to me! Just want to confirm if it works with live reload? i.e. when we are developing locally and after changing the placeholder, will the browser reloads correctly with the correct width?

2022-07-12 01:21 UTC, weiquu commented
> Hi, @weiquu sounds good to me! Just want to confirm if it works with live reload? i.e. when we are serving the site locally and after changing the placeholder, will the browser reload correctly with the correct width?

Yups, the browser will reload correctly with the correct width!

2022-07-13 07:21 UTC, ong6 approved these changes
LGTM, works on mac too

2022-07-17 14:56 UTC, jovyntls requested changes
The code looks good! I'm getting some FOUC errors, search bar appears twice then once:

https://user-images.githubusercontent.com/61113575/179404160-e8518ad6-1750-4b2a-9121-4e7ad3ff23d8.mov

2022-07-17 14:56 UTC, jovyntls commented on packages/vue-components/src/Searchbar.vue
> +        max-width: 25.4em;
What's the rationale for the max-width? I think it could help to add a comment to explain in case someone would want to change it in the future :)

2022-07-18 09:51 UTC, weiquu commented
Thanks @jovyntls for the comments! I've added an explanation to the max-width line, as well as hidden the temporary div so that only 1 search bar is seen.

2022-07-21 16:44 UTC, merged