Add expand and collapse all buttons in site-nav
MarkBind/markbind pull request #2206
Opened 2023-03-12 13:08 UTC by itsyme

**What is the purpose of this pull request?**

- [ ] Documentation update
- [ ] Bug fix
- [x] Feature addition or enhancement
- [ ] Code maintenance
- [ ] DevOps
- [ ] Improve developer experience
- [ ] Others, please explain:

**Overview of changes:**
Resolves #655. Added two buttons in site-nav to expand all and collapse all.

**Anything you'd like to highlight/discuss:**
Looking for suggestions to improve the look of the buttons as it may look slightly out of place now. Wondering if it should be toggle-able or only appear when there are dropdowns in site-nav.

**Testing instructions:**

**Proposed commit message: (wrap lines at 72 characters)**
Add expand and collapse all buttons in site-nav

---

**Checklist:** :ballot_box_with_check:

- [ ] Updated the documentation for feature additions and enhancements
- [ ] Added tests for bug fixes or features
- [x] Linked all related issues
- [x] No unrelated changes

2023-03-12 14:15 UTC, jovyntls commented
Some guidelines we could consider:
- Unobtrusive - preferably not "in my face" since the focus should be on our SiteNav contents
- Takes up minimal vertical space on top - we can try to keep the SiteNav contents as high up as possible since a user scanning the site nav starts from top to bottom. In other words, I think it would be good to avoid "pushing down" Sitenav contents 
- Would also be nice if authors can choose to hide/show the buttons on the SiteNav

Some ideas:
<img width="636" alt="Screenshot 2023-03-12 at 9 35 51 PM" src="https://user-images.githubusercontent.com/61113575/224549845-febe8372-5665-49ef-99e7-6d111cb5afb4.png">
<img width="636" alt="Screenshot 2023-03-12 at 9 35 51 PM" src="https://user-images.githubusercontent.com/61113575/224550220-bde7bcaf-b01f-4e4a-a08e-fd4fe96d2360.png">

Or we could style it more minimalist-y, similar to our current dropdown style, and have a single arrow beside the Sitenav title ("User Guide" in this case); it functions as an "Expand all" button initially, and when clicked it toggles between "Expand all" and "Collapse all"
<img width="636" alt="Screenshot 2023-03-12 at 9 35 51 PM" src="https://user-images.githubusercontent.com/61113575/224550049-9e79f7d4-f156-4b1d-b2e5-95295d6c1036.png">

At the bottom: 
<img width="602" alt="image" src="https://user-images.githubusercontent.com/61113575/224550388-26cfffe1-a891-4a61-a9d2-d3487af2ce8b.png">

2023-03-12 15:37 UTC, itsyme commented
Hi @jovyntls! Thanks for the feedback! I will try to implement the suggestions in due course. On the look of the buttons, I really like the first 3 implementations, however the location of the buttons are in the `site-nav-top` which iirc is optional. I will try implementing the buttons at the bottom. Any thoughts?

2023-03-12 16:26 UTC, jovyntls commented
@itsyme What do you think about making these buttons a component? This could allow users to choose whether or not they want to have the Expand/Collapse All buttons and give us more flexibility on where it can be added (including in optional components).

2023-03-12 16:50 UTC, itsyme commented
> @itsyme What do you think about making these buttons a component (like the scroll to top button)? This could allow users to choose whether or not they want to have the Expand/Collapse All buttons and give us more flexibility on where it can be added (including in optional components).

I think thats a great idea! I will try to implement that soon!

2023-04-02 03:12 UTC, jovyntls requested changes
This looks nice as a component! 
Not sure about having the component at the bottom with the up/down triangle arrows as it looks like it will trigger a scroll instead of a collapseAll/expandAll feature 😅

2023-04-02 03:12 UTC, jovyntls commented on docs/userGuide/syntax/collapseExpandButtons.md
> +<include src="codeAndOutput.md" boilerplate >
Can we add syntax highlighting to this code block?

2023-04-02 03:12 UTC, jovyntls commented on packages/vue-components/src/__tests__/CollapseExpandButtons.spec.js
Tests look good! Can I check if there are tests on sitenavs that have some expanded and some collapsed dropdowns?

2023-04-02 04:49 UTC, itsyme commented
> This looks nice as a component! Not sure about having the component at the bottom with the up/down triangle arrows as it looks like it will trigger a scroll instead of a collapseAll/expandAll feature 😅

Thanks for the feedback @jovyntls! I will explore other icons that might be more suited for this use case!

2023-04-02 04:50 UTC, itsyme commented on packages/vue-components/src/CollapseExpandButtons.vue
> +    .collapse-expand-expand-button {
I think that is a better name! Initially I had expand-button and collapse-button but that seemed to be conflicting with another class that's why I changed it to this!

2023-04-02 04:51 UTC, itsyme commented on packages/vue-components/src/__tests__/CollapseExpandButtons.spec.js
I think this would be a great addition to our current tests! I will implement it in the next commit!

2023-04-02 04:52 UTC, yucheng11122017 commented
Hi @itsyme, thanks for the work! Was wondering if it's possible to fix the position of the buttons to the bottom so it doesn't move up and down according to the length of the site nav?

2023-04-02 05:09 UTC, itsyme commented
> Hi @itsyme, thanks for the work! Was wondering if it's possible to fix the position of the buttons to the bottom so it doesn't move up and down according to the length of the site nav?

Hi @yucheng11122017! I on that! From my experimenting I think I would have to attach it to something else besides the site nav as my observation is that the height of the site nav changes with it's contents which can be seen in the line beside the site nav shortening together with the site nav.

2023-04-02 09:53 UTC, itsyme commented
Would something like this be better?

https://user-images.githubusercontent.com/71922282/229345575-00a690f3-2774-4569-928a-0297c663f7d5.mov

2023-04-02 10:09 UTC, yucheng11122017 commented
> This looks nice as a component! Not sure about having the component at the bottom with the up/down triangle arrows as it looks like it will trigger a scroll instead of a collapseAll/expandAll feature 😅

Hmmm I actually thought the up/down triangle arrows are not bad because its' consistent with the open and close button in the site nav. 

I kind of prefer that over the current icons in the updated video @itsyme 😅 but ok I see it looks very similiar to the current scroll up button 




> Would something like this be better? It would make the buttons have a fixed position rather than have a relative position

I think this looks good!

2023-04-02 10:11 UTC, itsyme commented
> > This looks nice as a component! Not sure about having the component at the bottom with the up/down triangle arrows as it looks like it will trigger a scroll instead of a collapseAll/expandAll feature 😅
> 
> Hmmm I actually thought the up/down triangle arrows are not bad because its' consistent with the open and close button in the site nav.
> 
> I kind of prefer that over the current icons in the updated video @itsyme 😅 but ok I see it looks very similiar to the current scroll up button
> 
> > Would something like this be better? It would make the buttons have a fixed position rather than have a relative position
> 
> I think this looks good!

what do you think about these instead?

<img width="292" alt="Screenshot 2023-04-02 at 6 10 51 PM" src="https://user-images.githubusercontent.com/71922282/229346585-691ec038-4455-44ae-837a-0fa3f1bd32fc.png">

2023-04-02 10:17 UTC, yucheng11122017 commented
> > > This looks nice as a component! Not sure about having the component at the bottom with the up/down triangle arrows as it looks like it will trigger a scroll instead of a collapseAll/expandAll feature 😅
> > 
> > 
> > Hmmm I actually thought the up/down triangle arrows are not bad because its' consistent with the open and close button in the site nav.
> > I kind of prefer that over the current icons in the updated video @itsyme 😅 but ok I see it looks very similiar to the current scroll up button
> 
> What do you think about these icons instead @yucheng11122017?
> 
> <img alt="Screenshot 2023-04-02 at 6 10 51 PM" width="292" src="https://user-images.githubusercontent.com/71922282/229346585-691ec038-4455-44ae-837a-0fa3f1bd32fc.png">

How about the plus and minus button that was mentioned by @jovyntls in her first comment?

2023-04-02 10:36 UTC, itsyme commented
> > > > This looks nice as a component! Not sure about having the component at the bottom with the up/down triangle arrows as it looks like it will trigger a scroll instead of a collapseAll/expandAll feature 😅
> > > 
> > > 
> > > Hmmm I actually thought the up/down triangle arrows are not bad because its' consistent with the open and close button in the site nav.
> > > I kind of prefer that over the current icons in the updated video @itsyme 😅 but ok I see it looks very similiar to the current scroll up button
> > 
> > 
> > What do you think about these icons instead @yucheng11122017?
> > <img alt="Screenshot 2023-04-02 at 6 10 51 PM" width="292" src="https://user-images.githubusercontent.com/71922282/229346585-691ec038-4455-44ae-837a-0fa3f1bd32fc.png">
> 
> How about the plus and minus button that was mentioned by @jovyntls in her first comment?
> 
> tbh if its at the top, would the triangles still seem like a scroll top scroll bottom button?

I felt like the plus and minus icons were a little too different from our present icons which are mostly from fontawesome, I will find a similar icon from fontawesome compare them!

2023-04-02 10:39 UTC, itsyme commented
These are some similar icons from fontawesome

1. <img width="300" alt="Screenshot 2023-04-02 at 6 37 34 PM" src="https://user-images.githubusercontent.com/71922282/229347813-390e0528-0f15-449e-8454-78b2a0fd9164.png">
1. <img width="301" alt="Screenshot 2023-04-02 at 6 38 21 PM" src="https://user-images.githubusercontent.com/71922282/229347848-d8186e07-28c9-4176-b56e-b49149c9d6bb.png">
1. <img width="300" alt="Screenshot 2023-04-02 at 6 38 53 PM" src="https://user-images.githubusercontent.com/71922282/229347871-d01807b4-748d-4e86-ab06-1228cc43ac8b.png">

2023-04-02 10:48 UTC, yucheng11122017 commented
> These are some similar icons from fontawesome
> 
> 1. <img alt="Screenshot 2023-04-02 at 6 37 34 PM" width="300" src="https://user-images.githubusercontent.com/71922282/229347813-390e0528-0f15-449e-8454-78b2a0fd9164.png">
> 2. <img alt="Screenshot 2023-04-02 at 6 38 21 PM" width="301" src="https://user-images.githubusercontent.com/71922282/229347848-d8186e07-28c9-4176-b56e-b49149c9d6bb.png">
> 3. <img alt="Screenshot 2023-04-02 at 6 38 53 PM" width="300" src="https://user-images.githubusercontent.com/71922282/229347871-d01807b4-748d-4e86-ab06-1228cc43ac8b.png">

Ooo I think these look a lot nicer! I think 2 fits with the site nav design :)

2023-04-02 12:01 UTC, jovyntls commented
> > This looks nice as a component! Not sure about having the component at the bottom with the up/down triangle arrows as it looks like it will trigger a scroll instead of a collapseAll/expandAll feature 😅
> 
> Hmmm I actually thought the up/down triangle arrows are not bad because its' consistent with the open and close button in the site nav.

I agree! I have no issues with the icons - more concerned about placing it at the bottom which would be disconnected from a shorter sitenav. Having it at the top right of the site nav looks good :)

2023-04-03 02:24 UTC, jovyntls reviewed
The code and tests LGTM! 😄  Remaining nits are on the documentation.

I'm not sure if this component should be under "others" or "navigation" (I can see how it may fall into either 🤔 ) Though I think it would be nice to add a note about this component under the "sitenav" section to improve feature discoverability. 

Also, "Collapse/Expand All Buttons" or "Collapse & Expand All Buttons" or "Collapse Expand All Buttons" be a nicer reader-facing name?

2023-04-03 03:12 UTC, itsyme commented
> The code and tests LGTM! 😄 Remaining nits are on the documentation.
> 
> I'm not sure if this component should be under "others" or "navigation" (I can see how it may fall into either 🤔 ) Though I think it would be nice to add a note about this component under the "sitenav" section to improve feature discoverability.
> 
> Also, "Collapse/Expand All Buttons" or "Collapse & Expand All Buttons" or "Collapse Expand All Buttons" be a nicer reader-facing name?

I think "Collapse/Expand All Buttons" sounds the most natural to me! I will change it in the next commit!

2023-04-03 06:31 UTC, jovyntls approved these changes
LGTM! Thank you @itsyme

2023-04-03 06:38 UTC, yucheng11122017 commented
Hi @itsyme, the documentation has an example but the buttons seem to collapse and expand the site nav at the side instead of at the example.

Understand that its part of the implementation but was thinking that it would be good to not have this example in that case and just say there is an example of the left of the page at the site nav. 

What do you think?

2023-04-03 07:05 UTC, itsyme commented
> Hi @itsyme, the documentation has an example but the buttons seem to collapse and expand the site nav at the side instead of at the example.
> 
> Understand that its part of the implementation but was thinking that it would be good to not have this example in that case and just say there is an example of the left of the page at the site nav.
> 
> What do you think?

I agree! I will make the appropriate changes in the next commit!

2023-04-04 09:57 UTC, yucheng11122017 approved these changes
LGTM except for one small nit! thanks for the work

2023-04-04 09:57 UTC, yucheng11122017 commented on packages/vue-components/src/__tests__/CollapseExpandButtons.spec.js
> +<nav id="site-nav">
Is it possible to indent the code here?

2023-04-04 10:12 UTC, yucheng11122017 commented on packages/vue-components/src/CollapseExpandButtons.vue
> +      <i :class="['far fa-plus-square']"></i>
I think you don't need :class here because its static not dynamic :) Same  for below!

2023-04-04 12:07 UTC, merged