Add intra-site link instructions to docs
MarkBind/markbind pull request #2276
Opened 2023-04-09 12:29 UTC by itsyme

**What is the purpose of this pull request?**

- [x] Documentation update
- [ ] Bug fix
- [ ] Feature addition or enhancement
- [ ] Code maintenance
- [ ] DevOps
- [ ] Improve developer experience
- [ ] Others, please explain:

**Overview of changes:**
Related to #2273. Added a section in "Contribute to Documentation" to explain the use tags when adding intra-site links. Added a box to "Implement a New Feature" to remind developers to use tags in intra-site links.

**Anything you'd like to highlight/discuss:**

**Testing instructions:**

**Proposed commit message: (wrap lines at 72 characters)**

---

**Checklist:** :ballot_box_with_check:

- [ ] Updated the documentation for feature additions and enhancements
- [ ] Added tests for bug fixes or features
- [x] Linked all related issues
- [x] No unrelated changes

2023-04-09 12:45 UTC, tlylt requested changes

2023-04-09 12:45 UTC, tlylt commented on docs/devGuide/bootcamp/contributeToDocs.md
> +## Adding Intra-Site Links to Documentation
Let's shift this into Workflow (create a Docs section in there), as the content included here is phrased in a BootCamp task manner.

2023-04-09 12:45 UTC, tlylt commented on docs/devGuide/bootcamp/contributeToDocs.md
> +Due to the way MarkBind's documentation is deployed, links from the developer guide that refer to the user guide, or vice versa, have to be differentiated with tags. MarkBind's documentation currentl
Can we add a note here that intra-site links within UG and DG need not add the tags

2023-04-09 12:45 UTC, tlylt commented on docs/devGuide/bootcamp/contributeToDocs.md
> +- `environment--combined` for locally served documentation
for deploying both the ug and dg tgt, I think that's the main point. It's not just locally served. It is also served on markbind-master, and during pr-preview

2023-04-09 12:45 UTC, tlylt commented on docs/devGuide/bootcamp/contributeToDocs.md
> +
can we add a brief intro to say what the following is about? examples?

2023-04-09 13:38 UTC, tlylt requested changes
Can we include the rationale of why the tags work? (the part about using absolute link vs relative link)?

2023-04-09 13:38 UTC, tlylt commented on docs/devGuide/development/workflow.md
> +#### Adding Intra-Site Links to Documentation
```suggestion
### Adding Intra-Site Links to Documentation
```

2023-04-09 13:38 UTC, tlylt commented on docs/devGuide/development/workflow.md
> +##### Developer Guide
```suggestion
#### Developer Guide
```

2023-04-09 13:38 UTC, tlylt commented on docs/devGuide/development/workflow.md
> +##### User Guide
```suggestion
#### User Guide
```

2023-04-09 15:10 UTC, tlylt approved these changes

2023-04-10 05:01 UTC, lhw-1 approved these changes
LGTM! Just some wording nits :)

2023-04-10 05:01 UTC, lhw-1 commented on docs/devGuide/development/workflow.md
> +Tags allow you to selectively filter content when building a site. Using them with the links helps to filter the correct link to be rendered for the right environment, ensuring that the correct link
```suggestion
To ensure that correct links are created, use tags with the links to selectively filter the correct link to be rendered for the right environment. When both the User Guide and the Developer Guide are deployed together, they have access to the files from each other, allowing the relative link to work. However, when they are deployed individually, this is not the case. Using absolute links creates the same effect as the relative link without having to have access to the files from the other guide.
```

2023-04-10 05:19 UTC, merged