Add missing page links to sitenav and workingWithSites overview
MarkBind/markbind pull request #2307
Opened 2023-06-13 15:22 UTC by EssWhyy

**What is the purpose of this pull request?**

- [x] Documentation update
- [ ] Bug fix
- [ ] Feature addition or enhancement
- [ ] Code maintenance
- [ ] DevOps
- [ ] Improve developer experience
- [ ] Others, please explain:

**Overview of changes:**
Fix #2219 (Add the "templates" page into the sitenav for more visibility)

**Anything you'd like to highlight/discuss:**
I have added the "templates" page to the sitenav and "Working With Sites" overview. I have also added the "Redirecting to 404" page section to the overview for consistency.

**Testing instructions:**

NA

**Proposed commit message: (wrap lines at 72 characters)**

Add missing page links to sitenav and workingWithSites overview

---

**Checklist:** :ballot_box_with_check:

- [ ] Updated the documentation for feature additions and enhancements
- [ ] Added tests for bug fixes or features
- [x] Linked all related issues
- [ ] No unrelated changes

2023-06-16 13:33 UTC, tlylt commented
> I have also added the "Redirecting to 404" page section to the overview for consistency.

Do you mean "Adding Navigation Buttons" page?

2023-06-16 13:37 UTC, tlylt requested changes
Thank you for updating the docs! To complete the inclusion of both Templates and Adding Navigation Buttons, will need you to also update their respective navigation button at the bottom of both pages.

E.g. this place:
![image](https://github.com/MarkBind/markbind/assets/41845017/16a6ebcd-ca10-4f39-a6db-61cda97af794)
![image](https://github.com/MarkBind/markbind/assets/41845017/efb9539f-ed0a-4a6f-a3b6-a74515683871)
Read this https://markbind-master.netlify.app/userguide/addingnavigationbuttons and see other examples for details.

2023-06-16 15:33 UTC, EssWhyy commented
Oh yep my mistake, yep I was referring to the Adding Navigation Buttons section, and yeah ok I will add in the navigation buttons for both pages

2023-06-18 00:00 UTC, tlylt commented on docs/userGuide/templates.md
> +  MarkBind allows you to start off your new project with different templates.
```suggestion
\
MarkBind allows you to start off your new project with different templates.
```

2023-06-18 00:10 UTC, tlylt commented
@EssWhyy btw for the PR description, note that to have GitHub detect and close an issue for you, you will need to use one of the closing keywords: "Fixes #xxx" or "Resolves #xxx" (at least for now, until they make it more intelligent with their new AI features). `Fix issue #2219` doesn't work (will need to remove the word "issue"), so `Fix #2219` will work.

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

Before:
![image](https://github.com/MarkBind/markbind/assets/41845017/bce24ddc-65d2-429a-9003-8c01607ef957)
After I edited the description:
![image](https://github.com/MarkBind/markbind/assets/41845017/21dda807-ccfb-4d01-b999-88d23e235d88)

2023-06-18 00:11 UTC, tlylt reviewed
LGTM

2023-06-18 00:11 UTC, tlylt approved these changes

2023-06-18 00:13 UTC, merged

2023-06-18 00:14 UTC, tlylt commented
@all-contributors please add @EssWhyy for doc