Fix issue 2222
MarkBind/markbind pull request #2319
Opened 2023-07-04 08:53 UTC by EssWhyy

**What is the purpose of this pull request?**

- [ ] Documentation update
- [ ] Bug fix
- [ ] Feature addition or enhancement
- [ ] Code maintenance
- [ ] DevOps
- [ ] Improve developer experience
- [x] Others, please explain:

Fixes #2222

**Overview of changes:**
I have modified the CSS modifiers for the panel cards button and bottom hr tags to reduce the empty space at the bottom of the panels. Intended effect is shown below. 

![Uploading possible panel css fix.png…]()

**Anything you'd like to highlight/discuss:**
I am not certain if the hr tag css I changed in NestedPanel.vue is the correct css. Since bootstrap.min.css also has a css for hr tags, but I'm not allowed to change it or it will fail tests.   

**Testing instructions:**
NA

**Proposed commit message: (wrap lines at 72 characters)**

Reduce margin spacing for panel collapse-button and hr tag

---

**Checklist:** :ballot_box_with_check:

- [ ] Updated the documentation for feature additions and enhancements
- [ ] Added tests for bug fixes or features
- [x] Linked all related issues
- [x] No unrelated changes

2023-07-04 14:28 UTC, tlylt commented
Thanks, @EssWhyy for tackling this.

> ![image](https://github.com/MarkBind/markbind/assets/41845017/d7040dbc-1036-417f-93bf-c90b7d54511c)

1. Image is broken

> I am not certain if the hr tag css I changed in NestedPanel.vue is the correct css. 

I think it sounds reasonable to change the CSS in NestedPanel, but any reason why `!important` is used and are there possible alternatives? An explanation for this would be useful as using !important unnecessarily might have unintended consequences.

> Since bootstrap.min.css also has a css for hr tags, but I'm not allowed to change it or it will fail tests.

Do you mean you edit the min.css file directly? what changes did you make and what tests are failing?

2023-07-08 15:56 UTC, EssWhyy commented
Hello @tlylt apologies for the late reply, here is the screenshot I meant to send. 

![possible panel css fix](https://github.com/MarkBind/markbind/assets/39799639/3cbc23ba-bc2b-423a-a2f6-6f83d557a972)

The use of !important tag was to override the bootstrap css for the hr tags. But I decided to remove them since the panel css should override it by default.

I initially tried to edit some hr css in markbind\packages\core-web\asset\css\bootstrap.min.css, but this leads to the markbind-cli:test failing. This probably is also not the best way to approach it since it affects all other hr tags.

There does not seem to be any panel in the user guide docs with a hr element, unlike the example in the issue which appears to be taken from the CS2103T website. Is there a specific class for the panels in CS2103T with the bottom hr lines?

2023-07-08 23:44 UTC, tlylt commented
> I initially tried to edit some hr css in markbind\packages\core-web\asset\css\bootstrap.min.css, but this leads to the markbind-cli:test failing. This probably is also not the best way to approach it since it affects all other hr tags.

yes I don't think you will ever need to edit the min.css file, unless upgrading bootstrap itself.

> There does not seem to be any panel in the user guide docs with a hr element, unlike the example in the issue which appears to be taken from the CS2103T website. Is there a specific class for the panels in CS2103T with the bottom hr lines?

Is this panel what you refer to as a panel with a hr element?
![image](https://github.com/MarkBind/markbind/assets/41845017/e392fd9c-34b3-4ab0-9968-6d1a35880894)

Besides the above, in the panel section, the distance between the button and the closing bottom line has been impacted. Is this intended by you? This UI change seems to not look as good when it's uniform across all panels.
![image](https://github.com/MarkBind/markbind/assets/41845017/616e81e5-0aff-42ff-b4ad-7f3c2d011f64)

Compare the before https://markbind-master.netlify.app/userguide/components/presentation#panels and after https://deploy-preview-2319--markbind-master.netlify.app/userguide/components/presentation#panels when doing your testing.

2023-07-09 06:50 UTC, damithc commented
@EssWhyy minor: can you update the PR title to be a more descriptive one?

2023-07-10 14:44 UTC, EssWhyy commented
For the latest commit I reverted my previous changes and added a new CSS selector within NestedPanel.vue to adjust the margins of the seamless panel hr directly. The effect is shown below.

![gap change](https://github.com/MarkBind/markbind/assets/39799639/bd7d45ce-d89b-45b4-ae8f-b448feb2add9)

2023-07-14 14:39 UTC, tlylt requested changes
Thanks @EssWhyy for following up on this. Review comments given.

Reference links:
- the page that contains the panel mentioned in the issue: https://nus-cs2103-ay2223s2.github.io/website/admin/tp-expectations.html (Expectation Do an equal share of the team-tasks.)
- some seamless panel in our UG: https://markbind-master.netlify.app/index.html (More examples of generating static content)

2023-07-14 14:39 UTC, tlylt commented on packages/vue-components/src/panels/NestedPanel.vue
> +            margin-top: 1rem;
```suggestion
            margin-top: 0.5rem;
```
This seems to achieve the same effect for larger screen. With 1rem:
![image](https://github.com/MarkBind/markbind/assets/41845017/5758fd07-8439-48c6-81e6-3b5cf54914b3)
But with 0.5rem:
![image](https://github.com/MarkBind/markbind/assets/41845017/c3353243-358c-42e1-b89c-92ee2ccdfd3a)

2023-07-14 14:39 UTC, tlylt commented on packages/vue-components/src/panels/NestedPanel.vue
> +        margin-bottom: 0.75rem;
```suggestion
```
Any reason why `margin-bottom` is adjusted? Doesn't seem to play any role in achieving the outcome

2023-07-15 09:08 UTC, tlylt approved these changes

2023-07-15 09:16 UTC, merged

2023-07-15 16:30 UTC, tlylt commented
@all-contributors please add @EssWhyy for code