Fix deploy error and deploy test case
MarkBind/markbind pull request #2346
Opened 2023-07-24 17:06 UTC by WillCWX

**What is the purpose of this pull request?**

- [ ] Documentation update
- [X] Bug fix
- [ ] Feature addition or enhancement
- [ ] Code maintenance
- [ ] DevOps
- [ ] Improve developer experience
- [ ] Others, please explain:

Close #2333
Related to #2331

**Overview of changes:**

- Migrate `Site/index.js` to `TypeScript` again.
- Change `options.remote` to be `defaultOptionConfig.remote` instead of `''`
  - This fixes the deploy error
- Remove `options.remote = defaultDeployConfig.remote` in `getDepUrl`
  - This fixes the false negative for the deploy test case 

**Anything you'd like to highlight/discuss:**

Nope

**Testing instructions:**

set up a test repo that with github pages 
run markbind deploy

**Proposed commit message: (wrap lines at 72 characters)**

Fix deploy error and deploy test case
---

**Checklist:** :ballot_box_with_check:

- [ ] Updated the documentation for feature additions and enhancements
- [ ] Added tests for bug fixes or features
- [X] Linked all related issues
- [X] No unrelated changes

2023-07-24 23:44 UTC, tlylt commented on packages/core/template/default/index.md
empty? same for a few more

2023-07-25 01:55 UTC, WillCWX commented on packages/core/template/default/index.md
I have no idea why it writes empty when the file is still there...

2023-07-25 02:01 UTC, WillCWX commented on packages/core/template/default/index.md
Apparently it is a windows vs linux / unix file thing: https://stackoverflow.com/questions/1257592/how-do-i-remove-files-saying-old-mode-100755-new-mode-100644-from-unstaged-cha

I'll see if I can remove that change from the commits

2023-07-25 02:47 UTC, WillCWX commented on packages/core/template/default/index.md
I fixed the file permissions back to 100755

2023-07-25 23:56 UTC, tlylt commented on packages/core/template/default/index.md
so what's the diff in this file? can we exclude it??

2023-07-25 23:56 UTC, tlylt commented on packages/core/template/default/site.json
> -}
same here can we remove this diff

2023-07-29 06:04 UTC, tlylt requested changes
Thank you @WillCWX for working on this PR. I have a few comments. Main issues:
- Could you take another look at the original PR and the changes made? https://github.com/MarkBind/markbind/pull/2270/files
  - I'm not sure why some changes (deletion, type assertions) that were made are not transferred back in this PR. I have pointed out a few places but I realized they are not done properly. If you have any concerns or comments as to why those are not necessary changes, please indicate for discussion.
- After everything is done, will need to re-organize into 2 commits as specified in the DG, one for rename, and one for migration. (Please rebase first as well)

2023-07-29 06:04 UTC, tlylt commented on packages/core/src/Site/index.ts
>     * if there is a change in the variables file
![image](https://github.com/MarkBind/markbind/assets/41845017/3c4783ec-ce59-4bce-a540-86feee28de06)

2023-07-29 07:32 UTC, WillCWX commented on packages/core/src/Site/index.ts
> +    } catch (err: any) {
There is no real issue here, just a stylistic choice.
I will change it back

2023-07-29 08:45 UTC, WillCWX commented
I've compared the current migration with the previous PR and also the v5.0.0 file and made the changes accordingly.
I have followed the previous versions, except for some small comment (deleting extra spaces) / positioning changes.

As requested, I've removed the comments noted and also all the `{Type}` in `@param {Type}`.

2023-07-29 16:14 UTC, WillCWX commented
If its ok, I'll merge with master to update the branch and then rebase into two commits as mentioned in the docs.

2023-07-29 23:19 UTC, tlylt commented
sure

2023-07-30 00:07 UTC, tlylt commented
👍 @WillCWX can organize and will merge after that's done

2023-07-30 05:38 UTC, tlylt approved these changes

2023-07-30 05:41 UTC, merged