Annotation content slot
MarkBind/markbind pull request #2427
Opened 2024-02-17 09:11 UTC by yucheng11122017

**What is the purpose of this pull request?**

- [ ] Documentation update
- [ ] Bug fix
- [X] Feature addition or enhancement
- [ ] Code maintenance
- [ ] DevOps
- [ ] Improve developer experience
- [ ] Others, please explain:

Resolves #2403

**Overview of changes:**
Enable markdown for content, header and label in annotation point

**Anything you'd like to highlight/discuss:**
Per the issue, I suggested renaming 'content' to something else because it is a little misleading. However, this would result in a breaking change. So will leave it as it is for now. 

**Testing instructions:**
Try to use markdown in content, header and label in annotation point

**Proposed commit message: (wrap lines at 72 characters)**
Enable markdown for content, header and label in annotation point

---

**Checklist:** :ballot_box_with_check:

- [X] Updated the documentation for feature additions and enhancements
- [X] Added tests for bug fixes or features
- [X] Linked all related issues
- [X] No unrelated changes 

---

**Reviewer checklist:**

Indicate the [SEMVER](https://semver.org/) impact of the PR:
- [ ] Major (when you make incompatible API changes)
- [ ] Minor (when you add functionality in a backward compatible manner)
- [ ] Patch (when you make backward compatible bug fixes)

At the end of the review, please label the PR with the appropriate label: `r.Major`, `r.Minor`, `r.Patch`.

Breaking change release note preparation (if applicable):
- To be included in the release note for any feature that is made obsolete/breaking

> Give a brief explanation note about:
>   - what was the old feature that was made obsolete
>   - any replacement feature (if any), and
>   - how the author should modify his website to migrate from the old feature to the replacement feature (if possible).

2024-02-17 14:23 UTC, yucheng11122017 commented
Been trying to add unit tests for annotation but having problems with stubbing `v-popover`. 
When I try to stub it, it simply creates an empty tag, hence all the annotation points are missing. 
Would appreciate any advice on this :)

2024-02-22 13:46 UTC, EltonGohJH requested changes
Hi @yucheng11122017,

I tested the changes on my end wdyt of the requested changes?
From my observations
1. If you look at the annotatepoint, it is waiting for it to be fully mounted before rendering (waiting for isMounted flag to fully render). 
So, the solution I used wait for dom changes. It works but I think it might not be the recommended practice. (I think it is fine since it is deterministic)
You can try other methods from here (I think other methods do not really wait for child component to be mounted. So, I am not sure if there are any other methods) https://v1.test-utils.vuejs.org/guides/testing-async-components.html

2. v-postpover = dropdown from floating-vie

2024-02-22 13:46 UTC, EltonGohJH commented on packages/vue-components/src/__tests__/Annotation.spec.js
> +  'v-popover': true,
import { Dropdown } from 'floating-vue';

v-popover = Dropdown

2024-02-22 13:46 UTC, EltonGohJH commented on packages/vue-components/src/__tests__/Annotation.spec.js
> +
I tried this and this works. This waits for dom changes. (We are waiting for child components to be mounted)
`await wrapper.vm.$nextTick(); `

(Add to the rest if you are using this method!)

2024-02-24 06:13 UTC, EltonGohJH commented
![image](https://github.com/MarkBind/markbind/assets/75515229/b295bcf4-c7f2-426f-9c5f-780d951a56ce)
@yucheng11122017 
There is also a weird tooltip artefact on click. Is this a separate bug?

2024-02-24 06:16 UTC, yucheng11122017 commented
> ![image](https://private-user-images.githubusercontent.com/75515229/307499844-b295bcf4-c7f2-426f-9c5f-780d951a56ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3NTU2NjMsIm5iZiI6MTcwODc1NTM2MywicGF0aCI6Ii83NTUxNTIyOS8zMDc0OTk4NDQtYjI5NWJjZjQtYzdmMi00MjZmLTljNWYtNzgwZDk1MWE1NmNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI0VDA2MTYwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkMTg4M2JlYThhZTU4OWE3ZTJjNjUwZWM2ZDQ2NDJmMWI5YTNlNGFjZDk4NjdkYzFiZTQ2YWJjYmM5YmFlNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DSQ17E69bmZh-gIxGtY-mWYrli8O0hmpv28QOxdH1Yc) @yucheng11122017 There is also a weird tooltip artefact on click. Is this a separate bug?

Yup I noticed that prior to this PR - basically the popover is still present even though there is no content and header which resulted in that arrow

2024-02-24 06:28 UTC, merged