Add documentation regarding security practices for github actions
MarkBind/markbind pull request #2528
Opened 2024-04-23 17:06 UTC by KevinEyo1

**What is the purpose of this pull request?**

- [X] Documentation update
- [ ] Bug fix
- [ ] Feature addition or enhancement
- [ ] Code maintenance
- [ ] DevOps
- [ ] Improve developer experience
- [ ] Others, please explain:

**Overview of changes:**
Resolves #2515 
#2488 
**Anything you'd like to highlight/discuss:**
Only included the research of practices currently being used, so things like version tagging is not documented.

**Testing instructions:**

**Proposed commit message: (wrap lines at 72 characters)**
When writing GitHub action workflows, developers might miss 
out on security conventions.

Let's document current security practices in our developer guide 
so that future developers can follow these conventions.

---

**Checklist:** :ballot_box_with_check:

- [ ] Updated the documentation for feature additions and enhancements
- [ ] Added tests for bug fixes or features
- [X] Linked all related issues
- [X] No unrelated changes 

---

**Reviewer checklist:**

Indicate the [SEMVER](https://semver.org/) impact of the PR:
- [ ] Major (when you make incompatible API changes)
- [ ] Minor (when you add functionality in a backward compatible manner)
- [ ] Patch (when you make backward compatible bug fixes)

At the end of the review, please label the PR with the appropriate label: `r.Major`, `r.Minor`, `r.Patch`.

Breaking change release note preparation (if applicable):
- To be included in the release note for any feature that is made obsolete/breaking

> Give a brief explanation note about:
>   - what was the old feature that was made obsolete
>   - any replacement feature (if any), and
>   - how the author should modify his website to migrate from the old feature to the replacement feature (if possible).

2024-04-24 01:32 UTC, itsyme requested changes
Thanks for the work on creating documentation for github actions security! Pretty clear with only some nits!

2024-04-24 01:32 UTC, itsyme commented on docs/devGuide/githubActions/workflowSecurity.md
> +<div class="lead">
Remember to have a closing div tag at the correct place!

2024-04-24 01:32 UTC, itsyme commented on docs/devGuide/githubActions/workflowSecurity.md
> +Maximum access for pull requests from public forked repositories is read access due to security reasons. Since MarkBind uses the forking workflow, this leads to limitations in the CI/CD pipeline.
```suggestion
Read access is the most permissive access to be given for pull requests from public forked repositories to maintain security. Since MarkBind uses the forking workflow, this leads to limitations in the CI/CD pipeline. 
```

2024-04-24 01:32 UTC, itsyme commented on docs/devGuide/githubActions/workflowSecurity.md
> +When a workflow is triggered by the `pull_request_target` event, the `GITHUB_TOKEN` is granted read/write repository permission, even when it is triggered from a public fork. However, this could lead
```suggestion
When a workflow is triggered by the `pull_request_target` event, the `GITHUB_TOKEN` is granted read/write repository permission, even when it is triggered from a public fork. This could lead to security vulnerabilities if not handled properly.
```

2024-04-24 01:32 UTC, itsyme commented on docs/devGuide/githubActions/workflowSecurity.md
> +Another solution that allows `pull_request_target` to work securely with `actions/checkout` used on the pull request branch, is to add an additional step of running workflow only on approval by trust
Perhaps paraphrasing this sentence into a few shorter sentences could make it more readable

2024-04-24 03:35 UTC, yucheng11122017 reviewed
Thanks for the work @KevinEyo1! Some nits

2024-04-24 03:35 UTC, yucheng11122017 commented on docs/devGuide/githubActions/workflowSecurity.md
> +<box type="tip" light>
```suggestion
<box type="tip" light seamless>
```

2024-04-24 03:35 UTC, yucheng11122017 commented on docs/devGuide/githubActions/workflowSecurity.md
> +Use the ‘permissions’ key to make sure the `GITHUB_TOKEN` is configured with the least privileges for each job.
Could you add a code example of this? Where permissions is added

2024-04-24 03:35 UTC, yucheng11122017 commented on docs/devGuide/githubActions/workflowSecurity.md
> +Maximum access for pull requests from public forked repositories is read access due to security reasons. Since MarkBind uses the forking workflow, this leads to limitations in the CI/CD pipeline.
Do we need the line about limitations in the CI/CD pipeline? 
If yes, I'd rather put it in an info box and add more details about what the limitations are

2024-04-24 03:35 UTC, yucheng11122017 commented on docs/devGuide/githubActions/workflowSecurity.md
> +```
Can we add indentation for this

2024-04-24 03:35 UTC, yucheng11122017 commented on docs/devGuide/githubActions/workflowSecurity.md
> +```
Can we add indentation for this

2024-04-24 03:35 UTC, yucheng11122017 commented on docs/_markbind/layouts/devGuide.md
>  * [Project management]({{baseUrl}}/devGuide/projectManagement.html)
Remember to update the footer for project management as well

2024-04-24 12:45 UTC, itsyme commented on docs/devGuide/githubActions/workflowSecurity.md
> +**Here are some best practices to follow when working on GitHub Actions workflows.**
I would prefer if the div ends after this line as I feel like this bold small words looks a bit awkward

2024-04-24 16:00 UTC, yucheng11122017 reviewed
Some nits and clarification!

2024-04-24 16:00 UTC, yucheng11122017 commented on docs/devGuide/githubActions/workflowSecurity.md
> +
Can add a line saying like example or somethin?

2024-04-24 16:00 UTC, yucheng11122017 commented on docs/devGuide/githubActions/workflowSecurity.md
> +{% endraw %}
Why is the endraw here? Shouldn;t it be before the text?

2024-04-24 16:00 UTC, yucheng11122017 commented on docs/devGuide/githubActions/workflowSecurity.md
> +This can be fixed by adding code to ensure that the code being checked out belongs to the base branch.
Sorry what do you mean by 'code being checked out'?

2024-04-24 16:00 UTC, yucheng11122017 commented on docs/devGuide/githubActions/workflowSecurity.md
> +Another solution that allows `pull_request_target` to work securely with `actions/checkout` used on the pull request branch, is to implement running workflow only on approval by trusted users, such t
```suggestion
Another solution that allows `pull_request_target` to work securely with `actions/checkout` on the pull request branch, is to implement running workflow only on approval by trusted users. This means that the workflow is only run after a user has checked for malicious code on the feature branch manually and approves the run. 
```

2024-04-25 07:45 UTC, yucheng11122017 commented on docs/devGuide/githubActions/workflowSecurity.md
> +This method could be limiting since the code checked out is not up to date for the pull request. This means that the code checked out is not the code that is being tested. This could lead to false po
Can you rephrase the code checked out here also!

2024-04-25 10:26 UTC, yucheng11122017 approved these changes
LGTM! Thanks for the work

2024-04-25 11:52 UTC, itsyme approved these changes
LGMT! Thanks for the work!

2024-04-25 12:05 UTC, merged